[pytest]
filterwarnings =
    ignore::DeprecationWarning

env =
    SECRET_KEY=wG063Km5IlmuDKFSyIils71xbDgXhpOh
    # db
    D:DB__HOST=localhost
    DB__PORT=5432
    DB__USER=postgres
    DB__PASSWORD=postgres
    DB__NAME=test
    # storage
    D:STORAGE__S3__ENDPOINT=localhost
    STORAGE__S3__PORT=9000
    STORAGE__S3__AWS_ACCESS_KEY_ID=admin
    STORAGE__S3__AWS_SECRET_ACCESS_KEY=12345678
    STORAGE__S3__BUCKET=test
    STORAGE__S3__SECURE=false
    # cache
    CACHE__PROVIDER=redis
    CACHE__PREFIX=fast-clean
    D:CACHE__REDIS__DSN=redis://localhost:6379/0
